CREATE DATABASE CRUD;

USE CRUD;

CREATE TABLE IF NOT EXISTS tb_grupo(
id INT NOT NULL AUTO_INCREMENT,
descripcion VARCHAR(100),
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS tb_planCuenta(
id INT  NOT NULL AUTO_INCREMENT,
codigo VARCHAR(10) NOT NULL,
grupo  INT NOT NULL,
descripcion VARCHAR(100) NOT NULL,
naturaleza CHAR(1) NOT NULL,
estado BOOL,
PRIMARY KEY(id),
FOREIGN KEY(grupo) REFERENCES tb_grupo(id)
);

